 
RoleInfo = [
    { id: 0, label: "Sabori", shape: "", group: 17,color:"black" },
    { id: 2, label: "Asuka", shape: "", group: 17, },
    { id: 3, label: "Nika", shape: "", group: 17, },
    { id: 4, label: "小糖人", shape: "", group: 17, },
    { id: 5, label: "月球三眼女外星人", shape: "", group: 17, },
    { id: 6, label: "小糖人", shape: "", group: 17, },
    { id: 7, label: "G-man", shape: "", group: 17, },
    { id: 8, label: "楚", shape: "", group: 4, },
    { id: 9, label: "韩", shape: "", group: 4, },
    { id: 10, label: "齐", shape: "", group: 4, },
    { id: 11, label: "秦", shape: "", group: 4, },
    { id: 12, label: "魏", shape: "", group: 4, },
    { id: 13, label: "燕", shape: "", group: 4, },
    { id: 14, label: "赵", shape: "", group: 4, },
    { id: 15, label: "赵海飞", shape: "", group: 4, },
    { id: 16, label: "所有Except?.", shape: "", group: 4, },
    { id: 17, label: "亚特兰蒂斯", shape: "", group: 4, },
    { id: 18, label: "张超母亲", shape: "", group: 4, },
    { id: 19, label: "王峥母亲", shape: "", group: 4, },
    { id: 20, label: "王瑞棋", shape: "", group: 4, },
    { id: 21, label: "吴金春", shape: "", group: 4, },
    { id: 22, label: "Jacky Wu", shape: "", group: 4, },
    { id: 23, label: "吴潇涵", shape: "", group: 4, },
    { id: 24, label: "郑岩", shape: "", group: 4, },
    { id: 25, label: "吴潇涵", shape: "", group: 4, },
    { id: 26, label: "习近平", shape: "", group: 3, },
    { id: 27, label: "李克强", shape: "", group: 3, },
    { id: 28, label: "栗战书", shape: "", group: 3, },
    { id: 29, label: "汪洋", shape: "", group: 3, },
    { id: 30, label: "王沪宁", shape: "", group: 3, },
    { id: 31, label: "赵乐际", shape: "", group: 3, },
    { id: 32, label: "韩正", shape: "", group: 3, },
    { id: 33, label: "王岐山", shape: "", group: 3, },
    { id: 34, label: "王岐山", shape: "", group: 3, },
    { id: 35, label: "奶奶", shape: "", group: 12, },
    { id: 36, label: "女娲", shape: "", group: 12, },
    { id: 37, label: "悟净", shape: "", group: 12, },
    { id: 38, label: "孙悟空", shape: "", group: 12, },
    { id: 39, label: "唐僧", shape: "", group: 12, },
    { id: 40, label: "哪吒三太子", shape: "", group: 12, },
    { id: 41, label: "盘古", shape: "", group: 12, },
    { id: 42, label: "女娲", shape: "", group: 12, },
    { id: 43, label: "阿波罗 ", shape: "", group: 12, },
    { id: 44, label: "玉皇大帝", shape: "", group: 12, },
    { id: 45, label: "Hades", shape: "", group: 12, },
    { id: 46, label: "阿舅", shape: "", group: 12, },
    { id: 47, label: "菩萨", shape: "", group: 21, },
    { id: 48, label: "千手观音", shape: "", group: 21, },
    { id: 49, label: "图帕克·印卡·尤潘基", shape: "", group: 21, },
    { id: 50, label: "观音菩萨", shape: "", group: 21, },
    { id: 51, label: "黑无常", shape: "", group: 21, },
    { id: 52, label: "白无常", shape: "", group: 21, },
    { id: 53, label: "地藏王菩萨", shape: "", group: 21, },
    { id: 54, label: "耶稣", shape: "", group: 20, },
    { id: 55, label: "真主安拉", shape: "", group: 20, },
    { id: 56, label: "释迦牟尼", shape: "", group: 20, },
    { id: 57, label: "尼姑", shape: "", group: 13, },
    { id: 58, label: "和尚", shape: "", group: 13, },
    { id: 59, label: "二子", shape: "", group: 13, },
    { id: 60, label: "郎咸平", shape: "", group: 13, },
    { id: 61, label: "柳仙", shape: "", group: 13, },
    { id: 62, label: "狐仙", shape: "", group: 13, },
    { id: 63, label: "黄仙", shape: "", group: 13, },
    { id: 64, label: "白仙", shape: "", group: 13, },
    { id: 65, label: "鼠神", shape: "", group: 13, },
    { id: 66, label: "蛇精", shape: "", group: 19, },
    { id: 67, label: "狐狸精", shape: "", group: 19, },
    { id: 68, label: "黄鼠狼", shape: "", group: 19, },
    { id: 69, label: "刺猬", shape: "", group: 19, },
    { id: 70, label: "灰鼠精", shape: "", group: 19, },
    { id: 71, label: "笔记本", shape: "", group: 18, },
    { id: 72, label: "何申宝", shape: "", group: 11, },
    { id: 73, label: "田怀森", shape: "", group: 11, },
    { id: 74, label: "张跃辉", shape: "", group: 11, },
    { id: 75, label: "奶奶", shape: "", group: 11, },
    { id: 76, label: "姥姥", shape: "", group: 11, },
    { id: 77, label: "姥爷", shape: "", group: 11, },
    { id: 78, label: "叔叔", shape: "", group: 11, },
    { id: 79, label: "叔叔的大女儿", shape: "", group: 11, },
    { id: 80, label: "叔叔的小女儿", shape: "", group: 11, },
    { id: 81, label: "大舅", shape: "", group: 11, },
    { id: 82, label: "二舅", shape: "", group: 11, },
    { id: 83, label: "三舅", shape: "", group: 11, },
    { id: 84, label: "四舅", shape: "", group: 11, },
    { id: 85, label: "五舅", shape: "", group: 11, },
    { id: 86, label: "爸爸", shape: "", group: 11, },
    { id: 87, label: "徐延杰", shape: "", group: 11, },
    { id: 88, label: "韩巨松", shape: "", group: 5, },
    { id: 89, label: "巩亮亮", shape: "", group: 14, },
    { id: 90, label: "张震爱", shape: "", group: 14, },
    { id: 91, label: "郑明雪", shape: "", group: 14, },
    { id: 92, label: "宁彦斌", shape: "", group: 14, },
    { id: 93, label: "王猛", shape: "", group: 14, },
    { id: 94, label: "赵传金", shape: "", group: 14, },
    { id: 95, label: "赵铁铮", shape: "", group: 14, },
    { id: 96, label: "刘伟明", shape: "", group: 14, },
    { id: 97, label: "朱雯", shape: "", group: 14, },
    { id: 98, label: "吴伟", shape: "", group: 14, },
    { id: 99, label: "爷爷", shape: "", group: 14, },
    { id: 100, label: "徐绍林", shape: "", group: 14, },
 

   

]
EdgeInfo = [
  
    { from: 1, to: 0, label: "佛教", },
    { from: 1, to: 1, label: "佛教", },
    { from: 1, to: 18, label: "佛教", },
    { from: 1, to: 40, label: "佛教", },
    { from: 1, to: 50, label: "佛教", },
    { from: 0, to: 51, label: "佛教", },
    { from: 0, to: 83, label: "佛教", },
    { from: 0, to: 84, label: "佛教", },
    { from: 0, to: 155, label: "佛教", },
    { from: 0, to: 228, label: "佛教", },
    { from: 0, to: 231, label: "佛教", },
    { from: 3, to: 55, label: "共产党", },
    { from: 3, to: 56, label: "共产党", },
    { from: 3, to: 57, label: "共产党", },
    { from: 3, to: 58, label: "共产党", },
    { from: 0, to: 59, label: "共产党", },
    { from: 0, to: 60, label: "共产党", },
    { from: 0, to: 61, label: "共产党", },
    { from: 0, to: 151, label: "共产党", },
    { from: 0, to: 196, label: "共产党", },
    { from: 0, to: 0, label: "家长", },
    { from: 0, to: 4, label: "家长", },
    { from: 0, to: 21, label: "家长", },
    { from: 0, to: 22, label: "家长", },
    { from: 0, to: 23, label: "家长", },
    { from: 0, to: 149, label: "家长", },
    { from: 0, to: 156, label: "家长", },
    { from: 0, to: 159, label: "家长", }, 
    { from: 0, to: 197, label: "家长", },
    { from: 0, to: 198, label: "家长", },
    { from: 0, to: 36, label: "老师", },
    { from: 0, to: 37, label: "老师", },
    { from: 0, to: 153, label: "老师", },
    { from: 0, to: 173, label: "老师", },
    { from: 0, to: 189, label: "老师", },
    { from: 0, to: 190, label: "老师", },
    { from: 0, to: 195, label: "老师", },
    { from: 0, to: 18, label: "历史人物", },
    { from: 0, to: 19, label: "历史人物", },
    { from: 0, to: 20, label: "历史人物", },
    { from: 0, to: 24, label: "邻居", },
    { from: 0, to: 25, label: "邻居", },
    { from: 0, to: 28, label: "邻居", },
    { from: 0, to: 29, label: "邻居", },
    { from: 0, to: 30, label: "邻居", },
    { from: 0, to: 31, label: "邻居", },
    { from: 0, to: 32, label: "邻居", },
    { from: 0, to: 33, label: "邻居", },
    { from: 0, to: 34, label: "邻居", },
    { from: 0, to: 200, label: "民主人士", },
    { from: 0, to: 201, label: "民主人士", }, 
    { from: 0, to: 204, label: "民主人士", },
    { from: 0, to: 199, label: "偶像", },
    { from: 0, to: 0, label: "朋友", },
    { from: 0, to: 0, label: "朋友", },
    { from: 0, to: 39, label: "朋友", },
    { from: 0, to: 73, label: "朋友", }, 
    { from: 0, to: 78, label: "朋友", },
    { from: 0, to: 175, label: "朋友", },
    { from: 0, to: 176, label: "朋友", }, 
    { from: 0, to: 183, label: "朋友", },
    { from: 0, to: 186, label: "朋友", },
    { from: 0, to: 148, label: "日本人", },
    { from: 0, to: 48, label: "神话人物", },
    { from: 0, to: 63, label: "神话人物", }, 
    { from: 0, to: 67, label: "神话人物", },
   
   
 
    { from: 0, to: 191, label: "仙家", },
    { from: 0, to: 192, label: "仙家", },
    { from: 0, to: 194, label: "仙家", },
    { from: 0, to: 212, label: "仙家", },
    { from: 0, to: 27, label: "亚特兰蒂斯", },
    { from: 0, to: 86, label: "亚特兰蒂斯", }, 
    { from: 0, to: 88, label: "亚特兰蒂斯", },
    { from: 0, to: 193, label: "亚特兰蒂斯", },
    { from: 0, to: 205, label: "亚特兰蒂斯", },
    { from: 0, to: 12, label: "伊斯兰教", },
    { from: 0, to: 13, label: "伊斯兰教", }, 
    { from: 0, to: 53, label: "伊斯兰教", },
    { from: 0, to: 89, label: "宗教领袖", },
    { from: 0, to: 90, label: "宗教领袖", },
    { from: 0, to: 41, label: "宗教人物", },
    { from: 0, to: 49, label: "宗教人物", },
    { from: 0, to: 169, label: "宗教人物", },
    { from: 0, to: 181, label: "宗教人物", },
    { from: 0, to: 185, label: "宗教人物", },

]

